name: tabpanel
description: Tabbed inferface with support for nested and resizeable panels.
version: 0.1.0
homepage: https://github.com/Rudiksz/tabpanel

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.2.2
  mobx: ^1.2.1+4 
  flutter_mobx: ^1.1.0+2

dev_dependencies:
  build_runner:
  mobx_codegen: ^1.0.0
  pedantic: ^1.0.0